version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build-and-deploy:
    docker:
      - image: "cimg/node:16.17.1"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End linting
          command: |
            npm run frontend:lint
     
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
