branch-defaults:
  main:
    environment: Awsbackend-env
  master:
    environment: Awsbackend-env
    group_suffix: null
global:
  application_name: aws-backend
  branch: main
  default_ec2_keyname: aws-eb2
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
